### ISSUE TITLE
"Run as" does not work from package explorer, just at project explorer

### ISSUE THREAD

**Issue by sombriks** [eclipse/thym#28]
fedora 21, java 7, eclipse luna, thym from marketplace.

don't know where to look to find a solution.

**Comment by mickaelistria** [comment]
For non Java-only projects, it's definitely recommended to use Project Explorer anyway.

**Comment by sombriks** [comment]
i understand.

actually i converted the project to a faceted one (due to multiple platform targets), that's why i have a need on package explorer.

**Comment by mickaelistria** [comment]
I'm curious about it: what's the feature of Package Explorer that you're missing in Project Explorer? Can you file a bugzilla for it and link it from https://bugs.eclipse.org/bugs/show_bug.cgi?id=427897 ?

**Comment by sombriks** [comment]
sometimes my project explorer make eclipse slow. so i've tried to use the package exploer, and my hunch was right.

seeing the bug, it's better to mark it as wontfix, since sooner or later package explorer will cease to exists.

**Comment by mickaelistria** [comment]
> seeing the bug, it's better to mark it as wontfix, since sooner or later package explorer will cease to exists.

Package Explorer will not disappear very soon since there is still much work to do, so if there is some value and low effort to fix the issue you created, it's still worth keeping it.
@gorkem WDYT?

**Comment by gorkem** [comment]
JDT is not a Thym dependency, I would not like to add it. We need to think of a way of fixing it without adding that dependency.

**Comment by gorkem** [comment]
filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=462505 
closing this one
