### ISSUE TITLE
versionCode not work

### ISSUE THREAD

**Issue by Sirioxstar** [eclipse/thym#42]
hi,
I upgraded my app but the file AndroidManifest.xml versionCode is always 1.0. I can not change it. can you help me? thank you!

**Comment by gorkem** [comment]
Unfortunately versionCode is not supported yet but it will be in the next version(2.0). ATM the workaround is to export your project and manually edit.

**Comment by gorkem** [comment]
with the move to use Cordova CLI on Thym 2.0 (Neon) this is supported
