### ISSUE TITLE
My project not running on Cordova Sim

### ISSUE THREAD

**Issue by Mrabtei** [eclipse/thym#44]
I created my Hybrid Project on the latest update of Thym and when I try to run it on Cordova Sim I get this error 
An internal error occurred during: "Launching...." org.eclipse.thym.core.HybridProject.getActiveEngine()Lorg/eclipse/thym/core/engine/HybridMobileEngine;

**Comment by mickaelistria** [comment]
It seems like you have some incompatible versions installed.. Can you check that the version of Thym bundles under the plugins/ directory match and are the same than with latest update?

**Comment by Mrabtei** [comment]
I created a project with no plugins so it generated under the plugin directory a Whitelist and two files android.json and fetch.json.

**Comment by mickaelistria** [comment]
Sorry, I was talking about the Eclipse plugins, under eclipse/plugins directory; not about the cordova ones.

**Comment by Mrabtei** [comment]
org.eclipse.thym.core_0.1.0.201503051642  is this the latest update ?

**Comment by Mrabtei** [comment]
Ok I found the problem I was downloading updates from   http://download.eclipse.org/thym/snapshots .
