### ISSUE TITLE
Building target for android 

### ISSUE THREAD

**Issue by Mrabtei** [eclipse/thym#47]
I want to build my hybrid application for Android API 21 and Eclipse requires Android API 23 
The Android api that I installed : 
![1](https://cloud.githubusercontent.com/assets/17646475/13699659/b693887c-e773-11e5-985b-1a4d9d65d293.PNG)
And the error I get :
![2](https://cloud.githubusercontent.com/assets/17646475/13699674/d6ccc680-e773-11e5-92c3-424cd5977ea0.PNG)

**Comment by Mrabtei** [comment]
@gorkem can you please give me some explanation about this issue , It's really confusing .

**Comment by gorkem** [comment]
When Thym compiles the cordova-android framework (the framework itself not your application) it looks at the project.properties [1] of the cordova-android your application is targeting. As you can see on [1] the target for cordova-android 5.1.0 is API level 23. 

[1] https://github.com/apache/cordova-android/blob/5.1.0/framework/project.properties

**Comment by Mrabtei** [comment]
So how can I change the target ? By changing the engine of cordova android ?

**Comment by Mrabtei** [comment]
@gorkem API level 23 is Android 6

**Comment by Mrabtei** [comment]
Ok I get it I should the engine of cordova Android Thank you @gorkem  for the reply.

**Comment by gorkem** [comment]
That is one way... Also you can change the project.properties file mentioned earlier. Thym does not have a way to specify target SDK version for a project, it simply trusts the cordova-android engine's configuration.
