### ISSUE TITLE
Cordova plugin registry: "Can not retrieve plugin catalog"

### ISSUE THREAD

**Issue by aleksander351** [eclipse/thym#98]
I think the url parsing should be updated:

[http://registry.npmjs.org/-/_view/byKeyword?startkey=%5B%22ecosystem:cordova%22%5D&endkey=%5B%22ecosystem:cordova1%22%5D&group_level=3"]

in **CordovaPluginRegistryManager.java** does not return any values anymore.

**Comment by rawagner** [comment]
Fixed with https://github.com/eclipse/thym/pull/99 You can try the latest snapshot http://download.eclipse.org/thym/snapshots
